server:
  port: 80

logging:
  level:
    com:
      jsj:
        member:
          ob:
            dao: info
#spring
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://172.16.5.102:3306/golden_ob?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: zhangning
      password: zhangning123
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 172.16.5.64
    port: 6379
    timeout: 10000
    pool:
      max-idle: 500
      max-wait: 500
      max-active: 1000
  rabbitmq:
    host: 172.16.5.64
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true

webconfig:
  # 图片服务器
  imgServerURL: http://img.jsjinfo.cn/upload
  # 是否上传到图片服务器 (true为上传到图片服务器 false为上传到本地服务器)
  imgServerSwitch: true
  # 公众号appid
  appId: wx555b169abb4d62ce
  # 公众号 appSecrect
  appSecrect: a8eb3f7e02ed7cb761220cb4363ff2b6

  #虚拟目录
  virtualPath: "/ob"
  #域名
  host: "http://h5.ktgj.com"

  #授权码
  PlatformAppId: ws975af9-2341-1234-9751-6ababc10aab3
  PlatformToken: wsscr975ppd8v46b5678f8fxh2xdhv0975xlx08h8btn6tt9754aab3

  #活动码地址
  activityUrl: http://172.16.6.134/awk/Third/ThirdApi/API2Partner.aspx

  partnerLoginName: guangxiyinlian
  partnerLoginPassword: gxylceshi

  WxTemplate:
    ##{{first.DATA}}
    ##订单号：{{keyword1.DATA}}
    ##商品名称：{{keyword2.DATA}}
    ##支付金额：{{keyword3.DATA}}
    ##{{remark.DATA}}
    PaySuccessed: 3fo6b1wXLfjep8kp0CKGwN7MVEIC-qO-fDPCTsQae2g


redis:
  host: 172.16.5.64
  port: 6379
  timeout: 10000
  pool-max-total: 1000
  pool-max-idle: 500
  pool-max-wait: 500
