server:
  port: 80

#spring
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://172.16.5.102:3306/golden_ob?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: zhangning
      password: zhangning123
      driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: 172.16.5.64
#    port: 6379
#    timeout: 10000
#    pool:
#      max-idle: 500
#      max-wait: 500
#      max-active: 1000
  rabbitmq:
    host: 172.16.5.64
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true

webconfig:

  # 公众号appid
  appId: wxe0942a1e2a5f53e3
  # 公众号 appSecrect
  appSecrect: 455c2d8d53c8cd37cca073e579fac95f

  ## 虚拟目录
  virtualPath: ""

  ## 严选活动码生成地址
  activityUrl: http://172.16.6.134/awk/Third/ThirdApi/API2Partner.aspx

  ## 开卡地址
  openCardUrl: http://172.16.6.134/awk/v3/ktapi/OpenVPCardFromWx

  ## 严选登录名
  partnerLoginName: jinseyanxuan
  ## 严选登录密码
  partnerLoginPassword: jinseyanxuan_123


redis:
  host: 172.16.5.64
  port: 6379
  timeout: 10000
  pool-max-total: 1000
  pool-max-idle: 500
  pool-max-wait: 500
